name: Node.js CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.3
      - name: Use Node.js 20.x
        uses: actions/setup-node@v1
        with:
          node-version: "20.x"
          cache: "npm"
      - run: npm install
      - run: npm run build --if-present

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist

# name: Node.js CI

# on:
#   push:
#     branches: ["main"]
#   pull_request:
#     branches: ["main"]

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v4  # Updated to version 4
#       - name: Use Node.js 20.x  # Updated to use Node.js 20
#         uses: actions/setup-node@v4
#         with:
#           node-version: '20'
#           cache: "npm"
#       - run: npm install
#       - run: npm run build --if-present

#       - name: Deploy
#         uses: peaceiris/actions-gh-pages@v3
#         with:
#           github_token:
#           publish_dir: ./dist